version: "3.7"

services:
  database:
    image: postgres
    container_name: database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=url_shortener
    volumes:
      - pgdata:/data/postgres


volumes:
  pgdata:
    driver: local